version: '3.1'

services:
  api_auth:
    restart: always
    container_name: api_auth
    build:
      context: ./repo-api-auth
    command: /bin/sh -c "go run main.go"
    stdin_open: true
    tty: true
    volumes:
      - ./repo-api-auth:/app
    ports:
      - 2356:2345
    depends_on:
      - db
    networks:
      - shared_network

  db:
    container_name: db_auth
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=release_dv_cp
    volumes:
      - db_auth_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - shared_network

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.13.3'
    container_name: elasticsearch_auth
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9100:9200"
    volumes:
      - es_auth_data:/usr/share/elasticsearch/data

volumes:
  db_auth_data:
  es_auth_data:

networks:
  shared_network:
    driver: bridge
