version: '3.1'

services:
  api_auth:
    restart: always
    container_name: api_auth
    build:
      context: .
    command: /bin/sh -c "go run main.go"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - 2356:2345
    networks:
      - shared_network

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.13.3'
    container_name: elasticsearch_auth
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9100:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - shared_network

volumes:
  esdata:
    driver: local

networks:
  shared_network:
    external: true
