version: '3.1'

services:
  api_auth:
    restart: always
    container_name: api_auth
    build:
      context: .
    command: /bin/sh -c "go run main.go"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - /opt/certs:/certs:ro    # Sertifikat HTTPS dimount read-only

    ports:
      - 2356:2345
    networks:
      - shared_network
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    container_name: elasticsearchauth
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 9500:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - shared_network

volumes:
  esdata:
    driver: local

networks:
  shared_network:
    external: true