version: '3.1'

services:
  api_auth:
    restart: always
    container_name: api_auth
    build:
      context: .
    command: /bin/sh -c "go run main.go"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - 2356:2345
    depends_on:
      - db
    networks:
      - shared_network

  db:
    container_name: db_shared
    image: postgres:14-alpine 
    environment: 
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes: 
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - shared_network

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.13.3'
    container_name: elasticsearch_shared
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - shared_network

volumes:
  db_data:
  esdata:
    driver: local

networks:
  shared_network:
    driver: bridge
